### ISSUE TITLE
Please, help me

### ISSUE THREAD

**Issue by OoHerbethoO** [alashow/datmusic-api#3]
API installed on my server, but it's not working ... What can be? Everything is set up correctly.

Thank you!

![captura de tela 2017-02-02 as 20 52 40](https://cloud.githubusercontent.com/assets/16544588/22573912/422c1250-e98a-11e6-8685-fe937fca345f.png)

**Comment by alashow** [comment]
As you can see in stacktrace, it aborts in `authSecurityCheck` function.

VK tries to verify user. As for now, this API can only verify phone number checks. 

You can verify it manually. Login from the same IP as your server (openvpn, socks5 proxy) and verify auth check manually.

But if you could get verification page, I could automate it.

To get output:
Add this line to [here](https://github.com/alashow/datmusic-api/blob/master/app/Datmusic/AuthenticatorTrait.php#L112):
```php
file_put_contents(storage_path("logs/auth_output.log"), $body);
```

Then send me file log file (rootfolder/storage/logs/auth_output.log).

Thanks.

**Comment by OoHerbethoO** [comment]
` <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="vk vk_js_no ">
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<meta name="format-detection" content="telephone=no" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="MobileOptimized" content="176" />
<meta name="HandheldFriendly" content="True" />
<base id="base">
<meta name="robots" content="noindex,nofollow" />
<title>Entrar | VK</title>
<link rel="shortcut icon" href="/images/icons/favicons/fav_logo.ico?6"></link>
<script>
(function() {
var html = document.querySelector('html');
html.setAttribute('class', html.getAttribute('class').replace('vk_js_no', 'vk_js_yes'));
})();
</script>
<script type="text/javascript">

</script>
<link type="text/css" rel="stylesheet" href="/css/s_c.css?307"></link>
<link type="text/css" rel="stylesheet" media="only screen" href="/css/s_yzg.css?188"></link>
<link rel="canonical" href="https://vk.com/login.php?act=security_check&to="></link>
<link rel="alternate" href="android-app://com.vkontakte.android/vkontakte/m.vk.com/login.php?act=security_check&to=" />
</head>
<body id="vk" class="vk__body _ivk _hover vk_stickers_hints_support_no opera_mini_no vk_al_no">
<div class="layout">
<div class="layout__header mhead" id="vk_head">
<div class="hb_wrap">
<div class="hb_btn">&nbsp;</div>
</div>
</div>
<div class="layout__body " id="vk_wrap">
<div class="layout__leftMenu" id="l">
</div>
<div class="layout__basis" id="m">
<div class="basis">
<div class="basis__header mhead" id="mhead"><a href="/login?act=do_logout&hash=11ef6a739c37aa9c6c" class="hb_wrap mhb_notify mh_nobl" accesskey="#">
<div class="hb_btn">
<em class="mh_btn_label">sair </em>
</div>
</a>
<a href="/" accesskey="*" class="hb_wrap mhb_logo mh_rb">
<div class="hb_btn mhi_logo">&nbsp;</div>
<h1 class="hb_btn mh_header">&nbsp;</h1>
</a></div>
<div class="basis__content mcont" id="mcont"><div class="pcont fit_box bl_cont">
<h4 class="sub_header">Teste de segurança</h4>
<div class="form_item fi_fat">
<div class="fi_row">Você está a tentar entrar com o nome <b>Herbeth-Santana Binho</b> de um local estranho.</div>
<div class="fi_row">Para confirmar que você é titular da página, por favor, indique <b>os dígitos que faltam no número</b> do telemóvel associado à página.</div>
<form method="post" action="/login.php?act=security_check&to=&hash=ba1b5dd4ae5dab8608">
<div class="fi_row">
<span class="field_prefix">+55</span>
<input type="text" class="textfield field_inline" name="code" style="width:75px;" />
<span class="field_prefix">&nbsp;08</span>
</div>
<div class="fi_row">
<input class="button" type="submit" value="Confirmar" /><div class="near_btn"><a href="/login?act=do_logout&hash=11ef6a739c37aa9c6c">Sair</a></div>
</div>
</form>
</div>
</div></div>
<div class="basis__footer mfoot" id="mfoot"><div class="pfoot">
<ul id="footer_menu" class="footer_menu">
<li class="fm_row"><a class="fm_item" href="/">Página principal</a></li>
<li class="fm_row"><a id="fv_link" class="fm_item fv_link" href="https://vk.com/login.php?act=security_check&to=&_fm=1">Versão completa</a></li>
<li class="fm_row"><a class="fm_item" href="/login?act=do_logout&hash=11ef6a739c37aa9c6c">Sair</a></li>
</ul>
</div></div>
<div class="_cntrs" style="height:0;overflow:hidden;">
<img width="1" height="1" src="//counter.yadro.ru/hit?uhttps%3A%2F%2Fm.vk.com%2Flogin.php%3Fact%3Dsecurity_check%26to%3D%26al_page%3D;r;53036424" alt="" align="left" />
<img width="1" height="1" src="//sb.scorecardresearch.com/p?c1=2&c2=13765216&c3=&c4=https%3A%2F%2Fm.vk.com%2Flogin.php%3Fact%3Dsecurity_check%26to%3D%26al_page%3D&c5=&c9=&c15=&cv=2.0&cj=1&rn=53036424" alt="" align="left" />
<img width="1" height="1" src="https://r3.mail.ru/k?vk_id=410789527&src=mobile&data=" />
<img src="//top-fwz1.mail.ru/counter?id=2579437;pid=410789527;r=" style="border:0;" height="1" width="1" />
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">

</script>
<div id="vk_utils"></div>
<div id="z"></div>
<div id="vk_bottom"></div>
</body>
</html>`

**Comment by OoHerbethoO** [comment]
Here is the output of the VK. 

![captura de tela 2017-02-03 as 01 55 40](https://cloud.githubusercontent.com/assets/16544588/22580042/e7da1dae-e9b3-11e6-976f-840ba879c805.png)
http://hpsweb.cf/auth_output.log

**Comment by alashow** [comment]
It should be working now.

Please let me now whether it works for you.

**Comment by OoHerbethoO** [comment]
Still does not work, is a white page but does not show the results.Thanks for the support!
![captura de tela 2017-02-03 as 03 36 24](https://cloud.githubusercontent.com/assets/16544588/22581872/f6eef4a0-e9c1-11e6-80cf-79d1ed53a1ff.png)

**Comment by alashow** [comment]
It's not a white page. It's 500 error.

Can you upload site/storage/logs/lumen.log?

**Comment by OoHerbethoO** [comment]
Was not creating any Lumen log file, I believe it is an error in the script :/

**Comment by alashow** [comment]
Is logs empty or what?

**Comment by OoHerbethoO** [comment]
Server not creating the log file with the registry of the alleged error.
![captura de tela 2017-02-03 as 03 51 42](https://cloud.githubusercontent.com/assets/16544588/22582229/4acb7632-e9c4-11e6-86b8-2b3aeca8fd45.png)

**Comment by alashow** [comment]
Okay, that is not normal.

Usually, Lumen can't write logs when it can't write to logs directory. But since file_put_contents worked, that shouldn't be the case (still you can check permissions).

Is there anything unusual in .env?

**Comment by OoHerbethoO** [comment]
Perfect! I was forgetting to change the directory permissions to "777", now everything is working perfectly. Thank you for your support and attention.

**Comment by alashow** [comment]
You are welcome.
